//
// *************************************************************************** //
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
// *************************************************************************** //
//
//
// *************************************************************************** //
// UnivDisasm library.
//
// This file is a part of UnivDisasm library.
//
// https://github.com/MahdiSafsafi/UnivDisasm
//
// The Original Code is GROUPS.dec.inc
//
// The Initial Developer of the Original Code is Mahdi Safsafi.
// Portions created by Mahdi Safsafi . are Copyright (C) 2015-2019 Mahdi Safsafi.
// All Rights Reserved.
// *************************************************************************** //
//

procedure Decode_GROUP_1(PInst: PInstruction); forward;
procedure Decode_GROUP_2(PInst: PInstruction); forward;
procedure Decode_GROUP_3(PInst: PInstruction); forward;
procedure Decode_GROUP_4(PInst: PInstruction); forward;
procedure Decode_GROUP_5(PInst: PInstruction); forward;
procedure Decode_GROUP_6(PInst: PInstruction); forward;
procedure Decode_GROUP_7(PInst: PInstruction); forward;
procedure Decode_GROUP_8(PInst: PInstruction); forward;
procedure Decode_GROUP_9(PInst: PInstruction); forward;
procedure Decode_GROUP_10(PInst: PInstruction); forward;
procedure Decode_GROUP_11(PInst: PInstruction); forward;
procedure Decode_GROUP_12(PInst: PInstruction); forward;
procedure Decode_GROUP_13(PInst: PInstruction); forward;
procedure Decode_GROUP_14(PInst: PInstruction); forward;
procedure Decode_GROUP_15(PInst: PInstruction); forward;
procedure Decode_GROUP_16(PInst: PInstruction); forward;
procedure Decode_GROUP_17(PInst: PInstruction); forward;
procedure Decode_GROUP_18(PInst: PInstruction); forward;
procedure Decode_GROUP_1A(PInst: PInstruction); forward;
procedure Decode_GROUP_XOP1(PInst: PInstruction); forward;
procedure Decode_GROUP_XOP2(PInst: PInstruction); forward;
procedure Decode_GROUP_XOP3(PInst: PInstruction); forward;
procedure Decode_GROUP_XOP4(PInst: PInstruction); forward;
